---
- name: "{{ method }} {{ item.name }} cleanup policy"
  ansible.builtin.uri:
    url: >
      {% if method in ['POST'] %}
        {{ nexus_protocol }}://{{ nexus_hostname }}:{{ nexus_port }}/service/rest/v1/cleanup-policies
      {% elif method in ['PUT', 'DELETE'] %}
        {{ nexus_protocol }}://{{ nexus_hostname }}:{{ nexus_port }}/service/rest/v1/cleanup-policies/{{ item.name }}
      {% endif %}
    method: "{{ method }}"
    validate_certs: false
    status_code: "{{ '201' if method == 'POST' else '204' }}"
    user: "{{ nexus_admin_username }}"
    password: "{{ nexus_admin_password }}"
    force_basic_auth: true
    body: "{{ item }}"
    body_format: json
  changed_when: true
  tags: cleanup-policies
