- name: Normalize pypi proxy repositories
  ansible.builtin.set_fact:
    nexus_repos_pypi_proxy_normalized: >
      {{ nexus_repos_pypi_proxy | cloudkrafter.nexus.normalize_repositories(
          nexus_repos_global_defaults,
          nexus_repos_type_defaults,
          nexus_repos_format_defaults,
          'proxy',
          'pypi',
          legacy_field_map
        ) }}
  tags:
    - pypi
    - pypi-proxy

- name: Normalize pypi hosted repositories
  ansible.builtin.set_fact:
    nexus_repos_pypi_hosted_normalized: >
      {{ nexus_repos_pypi_hosted | cloudkrafter.nexus.normalize_repositories(
          nexus_repos_global_defaults,
          nexus_repos_type_defaults,
          nexus_repos_format_defaults,
          'hosted',
          'pypi',
          legacy_field_map
        ) }}
  tags:
    - pypi
    - pypi-hosted

- name: Normalize pypi group repositories
  ansible.builtin.set_fact:
    nexus_repos_pypi_group_normalized: >
      {{ nexus_repos_pypi_group | cloudkrafter.nexus.normalize_repositories(
          nexus_repos_global_defaults,
          nexus_repos_type_defaults,
          nexus_repos_format_defaults,
          'group',
          'pypi',
          legacy_field_map
        ) }}
  tags: pypi

# Need filtered facts for existing repositories because the API has different endpoints for each type and format
- name: Filter existing PyPi repositories
  ansible.builtin.set_fact:
    __nxs_crnt_pypi_hstd__: "{{ __nxs_all_repos__.json | selectattr('format', 'equalto', 'pypi') | selectattr('type', 'equalto', 'hosted') | list }}"
    __nxs_crnt_pypi_prxy__: "{{ __nxs_all_repos__.json | selectattr('format', 'equalto', 'pypi') | selectattr('type', 'equalto', 'proxy') | list }}"
    __nxs_crnt_pypi_grp__: "{{ __nxs_all_repos__.json | selectattr('format', 'equalto', 'pypi') | selectattr('type', 'equalto', 'group') | list }}"
  tags: repositories

- name: Determine PyPi repositories to create
  ansible.builtin.set_fact:
    nxs_create_pypi_hosted_repos: "{{ nexus_repos_pypi_hosted_normalized | rejectattr('name', 'in', __nxs_crnt_pypi_hstd__ | map(attribute='name') | list) | list }}"
    nxs_create_pypi_proxy_repos: "{{ nexus_repos_pypi_proxy_normalized | rejectattr('name', 'in', __nxs_crnt_pypi_prxy__ | map(attribute='name') | list) | list }}"
    nxs_create_pypi_group_repos: "{{ nexus_repos_pypi_group_normalized | rejectattr('name', 'in', __nxs_crnt_pypi_grp__ | map(attribute='name') | list) | list }}"
  tags: repositories

- name: Determine PyPi repositories to delete
  ansible.builtin.set_fact:
    nxs_delete_pypi_hosted_repos: "{{ __nxs_crnt_pypi_hstd__ | rejectattr('name', 'in', nexus_repos_pypi_hosted_normalized | map(attribute='name') | list) | list }}"
    nxs_delete_pypi_proxy_repos: "{{ __nxs_crnt_pypi_prxy__ | rejectattr('name', 'in', nexus_repos_pypi_proxy_normalized | map(attribute='name') | list) | list }}"
    nxs_delete_pypi_group_repos: "{{ __nxs_crnt_pypi_grp__ | rejectattr('name', 'in', nexus_repos_pypi_group_normalized | map(attribute='name') | list) | list }}"
  tags: repositories

- name: Compare PyPi hosted repositories for changes
  ansible.builtin.set_fact:
    nxs_update_pypi_hosted_repos: "{{ nxs_update_pypi_hosted_repos + [item] }}"
  loop: "{{ nexus_repos_pypi_hosted_normalized | rejectattr('name', 'in', nxs_create_pypi_hosted_repos | map(attribute='name') | list) | list }}"
  when: >
    (__nxs_crnt_pypi_hstd__ | selectattr('name', 'equalto', item.name) | first) is not defined or
    (__nxs_crnt_pypi_hstd__ | selectattr('name', 'equalto', item.name) | first).format | default('pypi') != item.format | default('pypi') or
    (__nxs_crnt_pypi_hstd__ | selectattr('name', 'equalto', item.name) | first).type | default('hosted') != item.type | default('hosted') or
    (__nxs_crnt_pypi_hstd__ | selectattr('name', 'equalto', item.name) | first).online | default(true) != item.online | default(true) or
    (__nxs_crnt_pypi_hstd__ | selectattr('name', 'equalto', item.name) | first).cleanup.policyNames | default([]) | sort != item.cleanup.policyNames | default([]) | sort or
    (__nxs_crnt_pypi_hstd__ | selectattr('name', 'equalto', item.name) | first).storage.blobStoreName | default(omit) != item.storage.blobStoreName | default(None) or
    (__nxs_crnt_pypi_hstd__ | selectattr('name', 'equalto', item.name) | first).storage.strictContentTypeValidation | default(false) != item.storage.strictContentTypeValidation | default(false) or
    (__nxs_crnt_pypi_hstd__ | selectattr('name', 'equalto', item.name) | first).storage.writePolicy | default(omit) | upper != item.storage.writePolicy | default(None) | upper or
    (__nxs_crnt_pypi_hstd__ | selectattr('name', 'equalto', item.name) | first).component.proprietaryComponents | default(false) != item.component.proprietaryComponents | default(false)
  tags:
    - pypi
    - pypi-hosted

- name: Compare PyPi proxy repositories for changes
  ansible.builtin.set_fact:
    nxs_update_pypi_proxy_repos: "{{ nxs_update_pypi_proxy_repos + [item] }}"
  loop: "{{ nexus_repos_pypi_proxy_normalized | rejectattr('name', 'in', nxs_create_pypi_proxy_repos | map(attribute='name') | list) | list }}"
  # TODO: implement replication
  when: >
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first) is not defined or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).format | default('pypi') != item.format | default('pypi') or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).type | default('proxy') != item.type | default('proxy') or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).online | default(true) != item.online | default(true) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).storage.blobStoreName | default(omit) != item.storage.blobStoreName | default(None) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).storage.strictContentTypeValidation | default(false) != item.storage.strictContentTypeValidation | default(false) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).cleanup.policyNames | default([]) | sort != item.cleanup.policyNames | default([]) | sort or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).proxy.remoteUrl | default(omit) != item.proxy.remoteUrl | default(None) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).proxy.contentMaxAge | default(omit) != item.proxy.contentMaxAge | default(None) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).proxy.metadataMaxAge | default(omit) != item.proxy.metadataMaxAge | default(None) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).negativeCache.enabled | default(false) != item.negativeCache.enabled | default(false) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).negativeCache.timeToLive | default(omit) != item.negativeCache.timeToLive | default(None) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.blocked | default(false) != item.httpClient.blocked | default(false) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.autoBlock | default(false) != item.httpClient.autoBlock | default(false) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.retries | default(omit) != item.httpClient.connection.retries | default(None) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.userAgentSuffix | default(omit) != item.httpClient.connection.userAgentSuffix | default(None) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.timeout | default(omit) != item.httpClient.connection.timeout | default(None) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.enableCircularRedirects | default(false) != item.httpClient.connection.enableCircularRedirects | default(false) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.enableCookies | default(false) != item.httpClient.connection.enableCookies | default(false) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.useTrustStore | default(false) != item.httpClient.connection.useTrustStore | default(false) or
    (
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication is not none and
        item.httpClient.authentication is none
    ) or
    (
        (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication is none and
        item.httpClient.authentication is not none
    ) or
    (
        (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication is not none and
        item.httpClient.authentication is not none and
        (
            (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication.type | default(None) != item.httpClient.authentication.type | default(None) or
            (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication.username | default(None) != item.httpClient.authentication.username | default(None) or
            (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication.ntlmHost | default(None) != item.httpClient.authentication.ntlmHost | default(None) or
            (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication.ntlmDomain | default(None) != item.httpClient.authentication.ntlmDomain | default(None)
        )
    ) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).routingRuleName | default(omit) != item.routingRule | default(None) or
    (__nxs_crnt_pypi_prxy__ | selectattr('name', 'equalto', item.name) | first).pypi.removeQuarantined | default(false) != item.pypi.removeQuarantined | default(false)
  tags:
    - pypi
    - pypi-proxy

- name: Compare PyPi group repositories for changes
  ansible.builtin.set_fact:
    nxs_update_pypi_group_repos: "{{ nxs_update_pypi_group_repos + [item] }}"
  loop: "{{ nexus_repos_pypi_group_normalized | rejectattr('name', 'in', nxs_create_pypi_group_repos | map(attribute='name') | list) | list }}"
  when: >
    (__nxs_crnt_pypi_grp__ | selectattr('name', 'equalto', item.name) | first) is not defined or
    (__nxs_crnt_pypi_grp__ | selectattr('name', 'equalto', item.name) | first).format | default('pypi') != item.format | default('pypi') or
    (__nxs_crnt_pypi_grp__ | selectattr('name', 'equalto', item.name) | first).type | default('group') != item.type | default('group') or
    (__nxs_crnt_pypi_grp__ | selectattr('name', 'equalto', item.name) | first).online | default(true) != item.online | default(true) or
    (__nxs_crnt_pypi_grp__ | selectattr('name', 'equalto', item.name) | first).storage.blobStoreName | default(omit) != item.storage.blobStoreName | default(None) or
    (__nxs_crnt_pypi_grp__ | selectattr('name', 'equalto', item.name) | first).storage.strictContentTypeValidation | default(false) != item.storage.strictContentTypeValidation | default(false) or
    (__nxs_crnt_pypi_grp__ | selectattr('name', 'equalto', item.name) | first).group.memberNames | default([]) != item.group.memberNames | default([])
  tags: pypi

- name: Show nxs_create_pypi_hosted_repos
  ansible.builtin.debug:
    var: nxs_create_pypi_hosted_repos
  when: nexus_config_dry_run
  changed_when: nxs_create_pypi_hosted_repos | length > 0
  tags:
    - pypi
    - pypi-hosted

- name: Show nxs_update_pypi_hosted_repos
  ansible.builtin.debug:
    var: nxs_update_pypi_hosted_repos
  when: nexus_config_dry_run
  changed_when: nxs_update_pypi_hosted_repos | length > 0
  tags:
    - pypi
    - pypi-hosted

- name: Show nxs_delete_pypi_hosted_repos
  ansible.builtin.debug:
    var: nxs_delete_pypi_hosted_repos
  when: nexus_config_dry_run
  changed_when: nxs_delete_pypi_hosted_repos | length > 0
  tags:
    - pypi
    - pypi-hosted

- name: Show nxs_create_pypi_proxy_repos
  ansible.builtin.debug:
    var: nxs_create_pypi_proxy_repos
  when: nexus_config_dry_run
  changed_when: nxs_create_pypi_proxy_repos | length > 0
  tags:
    - pypi
    - pypi-proxy

- name: Show nxs_update_pypi_proxy_repos
  ansible.builtin.debug:
    var: nxs_update_pypi_proxy_repos
  when: nexus_config_dry_run
  changed_when: nxs_update_pypi_proxy_repos | length > 0
  tags:
    - pypi
    - pypi-proxy

- name: Show nxs_delete_pypi_proxy_repos
  ansible.builtin.debug:
    var: nxs_delete_pypi_proxy_repos
  when: nexus_config_dry_run
  changed_when: nxs_delete_pypi_proxy_repos | length > 0
  tags:
    - pypi
    - pypi-proxy

- name: Show nxs_create_pypi_group_repos
  ansible.builtin.debug:
    var: nxs_create_pypi_group_repos
  when: nexus_config_dry_run
  changed_when: nxs_create_pypi_group_repos | length > 0
  tags: pypi

- name: Show nxs_update_pypi_group_repos
  ansible.builtin.debug:
    var: nxs_update_pypi_group_repos
  when: nexus_config_dry_run
  changed_when: nxs_update_pypi_group_repos | length > 0
  tags: pypi

- name: Show nxs_delete_pypi_group_repos
  ansible.builtin.debug:
    var: nxs_delete_pypi_group_repos
  when: nexus_config_dry_run
  changed_when: nxs_delete_pypi_group_repos | length > 0
  tags: pypi

- name: Apply Pypi repository changes
  block:
    - name: Create configured PyPi Hosted repositories using Nexus API
      ansible.builtin.include_tasks: repositories-api.yml
      vars:
        repos: "{{ item | default([]) }}"
        format: pypi
        type: hosted
        method: POST
      with_items:
        - "{{ nxs_create_pypi_hosted_repos | default([]) }}"
      when: nxs_create_pypi_hosted_repos | length > 0
      tags:
        - pypi
        - pypi-hosted

    - name: Create configured PyPi Proxy repositories using Nexus API
      ansible.builtin.include_tasks: repositories-api.yml
      vars:
        repos: "{{ item | default([]) }}"
        format: pypi
        type: proxy
        method: POST
      with_items:
        - "{{ nxs_create_pypi_proxy_repos | default([]) }}"
      when: nxs_create_pypi_proxy_repos | length > 0
      tags:
        - pypi
        - pypi-proxy

    - name: Create configured PyPi Group repositories using Nexus API
      ansible.builtin.include_tasks: repositories-api.yml
      vars:
        repos: "{{ item | default([]) }}"
        format: pypi
        type: group
        method: POST
      with_items:
        - "{{ nxs_create_pypi_group_repos | default([]) }}"
      when: nxs_create_pypi_group_repos | length > 0
      tags: pypi

    - name: Update configured PyPi Hosted repositories using Nexus API
      ansible.builtin.include_tasks: repositories-api.yml
      vars:
        repos: "{{ item | default([]) }}"
        format: pypi
        type: hosted
        method: PUT
      with_items:
        - "{{ nxs_update_pypi_hosted_repos | default([]) }}"
      when: nxs_update_pypi_hosted_repos | length > 0
      tags:
        - pypi
        - pypi-hosted

    - name: Update configured PyPi Proxy repositories using Nexus API
      ansible.builtin.include_tasks: repositories-api.yml
      vars:
        repos: "{{ item | default([]) }}"
        format: pypi
        type: proxy
        method: PUT
      with_items:
        - "{{ nxs_update_pypi_proxy_repos | default([]) }}"
      when: nxs_update_pypi_proxy_repos | length > 0
      tags:
        - pypi
        - pypi-proxy

    - name: Update configured PyPi Group repositories using Nexus API
      ansible.builtin.include_tasks: repositories-api.yml
      vars:
        repos: "{{ item | default([]) }}"
        format: pypi
        type: group
        method: PUT
      with_items:
        - "{{ nxs_update_pypi_group_repos | default([]) }}"
      when: nxs_update_pypi_group_repos | length > 0
      tags: pypi

    - name: Delete PyPi Hosted repositories using Nexus API
      ansible.builtin.include_tasks: repositories-api.yml
      vars:
        repos: "{{ nxs_delete_pypi_hosted_repos | default([]) }}"
        format: pypi
        type: hosted
        method: DELETE
      with_items:
        - "{{ nxs_delete_pypi_hosted_repos | default([]) }}"
      when: nxs_delete_pypi_hosted_repos | length > 0 and nexus_enforce_desired_state | bool
      tags:
        - pypi
        - pypi-hosted

    - name: Delete PyPi Proxy repositories using Nexus API
      ansible.builtin.include_tasks: repositories-api.yml
      vars:
        repos: "{{ nxs_delete_pypi_proxy_repos | default([]) }}"
        format: pypi
        type: proxy
        method: DELETE
      with_items:
        - "{{ nxs_delete_pypi_proxy_repos | default([]) }}"
      when: nxs_delete_pypi_proxy_repos | length > 0 and nexus_enforce_desired_state | bool
      tags:
        - pypi
        - pypi-proxy

    - name: Delete PyPi Group repositories using Nexus API
      ansible.builtin.include_tasks: repositories-api.yml
      vars:
        repos: "{{ nxs_delete_pypi_group_repos | default([]) }}"
        format: pypi
        type: group
        method: DELETE
      with_items:
        - "{{ nxs_delete_pypi_group_repos | default([]) }}"
      when: nxs_delete_pypi_group_repos | length > 0 and nexus_enforce_desired_state | bool
      tags: pypi
  when: not nexus_config_dry_run
  tags:
    - pypi
    - pypi-hosted
    - pypi-proxy
