- name: Normalize Maven proxy repositories
  ansible.builtin.set_fact:
    nexus_repos_maven_proxy_normalized: >
      {{ nexus_repos_maven_proxy | cloudkrafter.nexus.normalize_repositories(
          nexus_repos_global_defaults,
          nexus_repos_type_defaults,
          nexus_repos_format_defaults,
          'proxy',
          'maven',
          legacy_field_map
        ) }}
  tags:
    - maven
    - maven-proxy

- name: Normalize Maven hosted repositories
  ansible.builtin.set_fact:
    nexus_repos_maven_hosted_normalized: >
      {{ nexus_repos_maven_hosted | cloudkrafter.nexus.normalize_repositories(
          nexus_repos_global_defaults,
          nexus_repos_type_defaults,
          nexus_repos_format_defaults,
          'hosted',
          'maven',
          legacy_field_map
        ) }}
  tags:
    - maven
    - maven-hosted

- name: Normalize Maven group repositories
  ansible.builtin.set_fact:
    nexus_repos_maven_group_normalized: >
      {{ nexus_repos_maven_group | cloudkrafter.nexus.normalize_repositories(
          nexus_repos_global_defaults,
          nexus_repos_type_defaults,
          nexus_repos_format_defaults,
          'group',
          'maven',
          legacy_field_map
        ) }}
  tags: maven

# Need filtered facts for existing repositories because the API has different endpoints for each type and format
- name: Filter existing repositories
  ansible.builtin.set_fact:
    __nxs_crnt_mvn_hstd__: "{{ __nxs_all_repos__.json | selectattr('format', 'equalto', 'maven2') | selectattr('type', 'equalto', 'hosted') | list }}"
    __nxs_crnt_mvn_prxy__: "{{ __nxs_all_repos__.json | selectattr('format', 'equalto', 'maven2') | selectattr('type', 'equalto', 'proxy') | list }}"
    __nxs_crnt_mvn_grp__: "{{ __nxs_all_repos__.json | selectattr('format', 'equalto', 'maven2') | selectattr('type', 'equalto', 'group') | list }}"
  tags: repositories

- name: Determine repositories to create
  ansible.builtin.set_fact:
    nxs_create_mvn_hosted_repos: "{{ nexus_repos_maven_hosted_normalized | rejectattr('name', 'in', __nxs_crnt_mvn_hstd__ | map(attribute='name') | list) | list }}"
    nxs_create_mvn_proxy_repos: "{{ nexus_repos_maven_proxy_normalized | rejectattr('name', 'in', __nxs_crnt_mvn_prxy__ | map(attribute='name') | list) | list }}"
    nxs_create_mvn_group_repos: "{{ nexus_repos_maven_group_normalized | rejectattr('name', 'in', __nxs_crnt_mvn_grp__ | map(attribute='name') | list) | list }}"
  tags: repositories

- name: Determine repositories to delete
  ansible.builtin.set_fact:
    nxs_delete_mvn_hosted_repos: "{{ __nxs_crnt_mvn_hstd__ | rejectattr('name', 'in', nexus_repos_maven_hosted_normalized | map(attribute='name') | list) | list }}"
    nxs_delete_mvn_proxy_repos: "{{ __nxs_crnt_mvn_prxy__ | rejectattr('name', 'in', nexus_repos_maven_proxy_normalized | map(attribute='name') | list) | list }}"
    nxs_delete_mvn_group_repos: "{{ __nxs_crnt_mvn_grp__ | rejectattr('name', 'in', nexus_repos_maven_group_normalized | map(attribute='name') | list) | list }}"
  tags: repositories

- name: Compare maven hosted repositories for changes
  ansible.builtin.set_fact:
    nxs_update_mvn_hosted_repos: "{{ nxs_update_mvn_hosted_repos + [item] }}"
  loop: "{{ nexus_repos_maven_hosted_normalized | list }}"
  when: >
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first) is not defined or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).format | default('maven2') != item.format | default('maven2') or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).type | default('hosted') != item.type | default('hosted') or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).online | default(true) != item.online | default(true) or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).cleanup.policyNames | default([]) | sort != item.cleanup.policyNames | default([]) | sort or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).storage.blobStoreName | default(omit) != item.storage.blobStoreName | default(None) or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).storage.strictContentTypeValidation | default(false) != item.storage.strictContentTypeValidation | default(false) or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).storage.writePolicy | default(omit) | lower != item.storage.writePolicy | default(None) | lower or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).maven.versionPolicy | default(omit) | lower != item.maven.versionPolicy | default(None) | lower or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).maven.layoutPolicy | default(omit) | lower != item.maven.layoutPolicy | default(None) | lower or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).maven.contentDisposition | default(omit) | lower != item.maven.contentDisposition | default(None) | lower or
    (__nxs_crnt_mvn_hstd__ | selectattr('name', 'equalto', item.name) | first).component.proprietaryComponents | default(false) != item.component.proprietaryComponents | default(false)
  tags:
    - maven
    - maven-hosted

- name: Compare maven proxy repositories for changes
  ansible.builtin.set_fact:
    nxs_update_mvn_proxy_repos: "{{ nxs_update_mvn_proxy_repos + [item] }}"
  loop: "{{ nexus_repos_maven_proxy_normalized | list }}"
  # TODO: implement replication
  when: >
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first) is not defined or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).format | default('maven2') != item.format | default('maven2') or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).type | default('proxy') != item.type | default('proxy') or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).online | default(true) != item.online | default(true) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).storage.blobStoreName | default(omit) != item.storage.blobStoreName | default(None) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).storage.strictContentTypeValidation | default(false) != item.storage.strictContentTypeValidation | default(false) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).proxy.remoteUrl | default(omit) != item.proxy.remoteUrl | default(None) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).proxy.contentMaxAge | default(omit) != item.proxy.contentMaxAge | default(None) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).proxy.metadataMaxAge | default(omit) != item.proxy.metadataMaxAge | default(None) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).negativeCache.enabled | default(false) != item.negativeCache.enabled | default(false) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).negativeCache.timeToLive | default(omit) != item.negativeCache.timeToLive | default(None) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.blocked | default(false) != item.httpClient.blocked | default(false) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.autoBlock | default(false) != item.httpClient.autoBlock | default(false) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.retries | default(omit) != item.httpClient.connection.retries | default(None) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.timeout | default(omit) != item.httpClient.connection.timeout | default(None) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.enableCircularRedirects | default(omit) != item.httpClient.connection.enableCircularRedirects | default(None) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.enableCookies | default(false) != item.httpClient.connection.enableCookies | default(false) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.useTrustStore | default(false) != item.httpClient.connection.useTrustStore | default(false) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.connection.userAgentSuffix | default(omit) != item.httpClient.connection.userAgentSuffix | default(None) or
    (
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication is not none and
        item.httpClient.authentication is none
    ) or
    (
        (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication is none and
        item.httpClient.authentication is not none
    ) or
    (
        (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication is not none and
        item.httpClient.authentication is not none and
        (
            (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication.type | default(None) != item.httpClient.authentication.type | default(None) or
            (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication.username | default(None) != item.httpClient.authentication.username | default(None) or
            (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication.preemptive | default(None) != item.httpClient.authentication.preemptive | default(None) or
            (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication.ntlmHost | default(None) != item.httpClient.authentication.ntlmHost | default(None) or
            (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).httpClient.authentication.ntlmDomain | default(None) != item.httpClient.authentication.ntlmDomain | default(None)
        )
    ) or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).maven.versionPolicy | default(omit) | lower != item.maven.versionPolicy | default(None) | lower or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).maven.layoutPolicy | default(omit) | lower != item.maven.layoutPolicy | default(None) | lower or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).maven.contentDisposition | default(omit) | lower != item.maven.contentDisposition | default(None) | lower or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).cleanup.policyNames | default([]) | sort != item.cleanup.policyNames | default([]) | sort or
    (__nxs_crnt_mvn_prxy__ | selectattr('name', 'equalto', item.name) | first).routingRuleName | default(omit) != item.routingRule | default(None)
  tags:
    - maven
    - maven-proxy

- name: Compare maven group repositories for changes
  ansible.builtin.set_fact:
    nxs_update_mvn_group_repos: "{{ nxs_update_mvn_group_repos + [item] }}"
  loop: "{{ nexus_repos_maven_group_normalized | list }}"
  when: >
    (__nxs_crnt_mvn_grp__ | selectattr('name', 'equalto', item.name) | first) is not defined or
    (__nxs_crnt_mvn_grp__ | selectattr('name', 'equalto', item.name) | first).format | default('maven2') != item.format | default('maven2') or
    (__nxs_crnt_mvn_grp__ | selectattr('name', 'equalto', item.name) | first).type | default('group') != item.type | default('group') or
    (__nxs_crnt_mvn_grp__ | selectattr('name', 'equalto', item.name) | first).online | default(true) != item.online | default(true) or
    (__nxs_crnt_mvn_grp__ | selectattr('name', 'equalto', item.name) | first).storage.blobStoreName | default(omit) != item.storage.blobStoreName | default(None) or
    (__nxs_crnt_mvn_grp__ | selectattr('name', 'equalto', item.name) | first).storage.strictContentTypeValidation | default(false) != item.storage.strictContentTypeValidation | default(false) or
    (__nxs_crnt_mvn_grp__ | selectattr('name', 'equalto', item.name) | first).group.memberNames | default([]) != item.group.memberNames | default([])
  tags: maven

- name: Show nxs_create_mvn_hosted_repos
  ansible.builtin.debug:
    var: nxs_create_mvn_hosted_repos | length
  tags:
    - maven
    - maven-hosted

- name: Show nxs_update_mvn_hosted_repos
  ansible.builtin.debug:
    var: nxs_update_mvn_hosted_repos | length
  tags:
    - maven
    - maven-hosted

- name: Show nxs_delete_mvn_hosted_repos
  ansible.builtin.debug:
    var: nxs_delete_mvn_hosted_repos | length
  tags:
    - maven
    - maven-hosted

- name: Show nxs_create_mvn_proxy_repos
  ansible.builtin.debug:
    var: nxs_create_mvn_proxy_repos | length
  tags:
    - maven
    - maven-proxy

- name: Show nxs_update_mvn_proxy_repos
  ansible.builtin.debug:
    var: nxs_update_mvn_proxy_repos | length
  tags:
    - maven
    - maven-proxy

- name: Show nxs_delete_mvn_proxy_repos
  ansible.builtin.debug:
    var: nxs_delete_mvn_proxy_repos | length
  tags:
    - maven
    - maven-proxy

- name: Show nxs_create_mvn_group_repos
  ansible.builtin.debug:
    var: nxs_create_mvn_group_repos | length
  tags: maven

- name: Show nxs_update_mvn_group_repos
  ansible.builtin.debug:
    var: nxs_update_mvn_group_repos | length
  tags: maven

- name: Show nxs_delete_mvn_group_repos
  ansible.builtin.debug:
    var: nxs_delete_mvn_group_repos | length
  tags: maven

- name: Create configured Maven Hosted repositories using Nexus API
  ansible.builtin.include_tasks: repositories-api.yml
  vars:
    repos: "{{ item | default([]) }}"
    format: maven
    type: hosted
    method: POST
  with_items:
    - "{{ nxs_create_mvn_hosted_repos | default([]) }}"
  when: nxs_create_mvn_hosted_repos | length > 0
  tags:
    - maven
    - maven-hosted

- name: Create configured Maven Proxy repositories using Nexus API
  ansible.builtin.include_tasks: repositories-api.yml
  vars:
    repos: "{{ item | default([]) }}"
    format: maven
    type: proxy
    method: POST
  with_items:
    - "{{ nxs_create_mvn_proxy_repos | default([]) }}"
  when: nxs_create_mvn_proxy_repos | length > 0
  tags:
    - maven
    - maven-proxy

- name: Create configured Maven Group repositories using Nexus API
  ansible.builtin.include_tasks: repositories-api.yml
  vars:
    repos: "{{ item | default([]) }}"
    format: maven
    type: group
    method: POST
  with_items:
    - "{{ nxs_create_mvn_group_repos | default([]) }}"
  when: nxs_create_mvn_group_repos | length > 0
  tags: maven

- name: Update configured Maven Hosted repositories using Nexus API
  ansible.builtin.include_tasks: repositories-api.yml
  vars:
    repos: "{{ item | default([]) }}"
    format: maven
    type: hosted
    method: PUT
  with_items:
    - "{{ nxs_update_mvn_hosted_repos | default([]) }}"
  when: nxs_update_mvn_hosted_repos | length > 0
  tags:
    - maven
    - maven-hosted

- name: Update configured Maven Proxy repositories using Nexus API
  ansible.builtin.include_tasks: repositories-api.yml
  vars:
    repos: "{{ item | default([]) }}"
    format: maven
    type: proxy
    method: PUT
  with_items:
    - "{{ nxs_update_mvn_proxy_repos | default([]) }}"
  when: nxs_update_mvn_proxy_repos | length > 0
  tags:
    - maven
    - maven-proxy

- name: Update configured Maven Group repositories using Nexus API
  ansible.builtin.include_tasks: repositories-api.yml
  vars:
    repos: "{{ item | default([]) }}"
    format: maven
    type: group
    method: PUT
  with_items:
    - "{{ nxs_update_mvn_group_repos | default([]) }}"
  when: nxs_update_mvn_group_repos | length > 0
  tags: maven

- name: Delete Maven Hosted repositories using Nexus API
  ansible.builtin.include_tasks: repositories-api.yml
  vars:
    repos: "{{ nxs_delete_mvn_hosted_repos | default([]) }}"
    format: maven
    type: hosted
    method: DELETE
  with_items:
    - "{{ nxs_delete_mvn_hosted_repos | default([]) }}"
  when: nxs_delete_mvn_hosted_repos | length > 0
  tags:
    - maven
    - maven-hosted

- name: Delete Maven Proxy repositories using Nexus API
  ansible.builtin.include_tasks: repositories-api.yml
  vars:
    repos: "{{ nxs_delete_mvn_proxy_repos | default([]) }}"
    format: maven
    type: proxy
    method: DELETE
  with_items:
    - "{{ nxs_delete_mvn_proxy_repos | default([]) }}"
  when: nxs_delete_mvn_proxy_repos | length > 0
  tags:
    - maven
    - maven-proxy

- name: Delete Maven Group repositories using Nexus API
  ansible.builtin.include_tasks: repositories-api.yml
  vars:
    repos: "{{ nxs_delete_mvn_group_repos | default([]) }}"
    format: maven
    type: group
    method: DELETE
  with_items:
    - "{{ nxs_delete_mvn_group_repos | default([]) }}"
  when: nxs_delete_mvn_group_repos | length > 0
  tags: maven
