name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_`&'

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    title:
      - '/feat:/i'

categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: 'Fixed'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch

exclude-contributors:
  - 'brianveltman'

template: |
  ## What’s Changed

  $CHANGES
