[project]
name = "nexus-ansible-collection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.4.0",
    "docker>=7.1.0",
    "filelock==3.16.1",
    "idna==3.10",
    "importlib-metadata==8.5.0",
    "iniconfig==2.0.0",
    "jinja2==3.1.5",
    "jmespath==1.0.1",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2024.10.1",
    "lockfile==0.12.2",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "mdurl==0.1.2",
    "molecule==24.9.0",
    "molecule-plugins==23.5.3",
    "mypy-extensions==1.0.0",
    "onigurumacffi==1.3.0",
    "packaging==24.2",
    "parsley==1.3",
    "pathspec==0.12.1",
    "pbr==6.1.0",
    "pexpect==4.9.0",
    "platformdirs==4.3.6",
    "pluggy==1.5.0",
    "ptyprocess==0.7.0",
    "pycparser==2.22",
    "pygments==2.18.0",
    "pyproject-api==1.8.0",
    "pytest==8.3.3",
    "pytest-ansible==24.9.0",
    "pytest-cov>=6.1.1",
    "pytest-mock>=3.0.0",
    "pytest-testinfra==10.1.1",
    "pytest-xdist==3.6.1",
    "python-daemon==3.1.0",
    "python-gnupg==0.5.3",
    "pyyaml==6.0.2",
    "referencing==0.35.1",
    "requests==2.32.3",
    "resolvelib==1.0.1",
    "rich==13.9.4",
    "rpds-py==0.21.0",
    "ruamel-yaml==0.18.6",
    "selinux==0.3.0",
    "setuptools==75.4.0",
    "subprocess-tee==0.4.2",
    "tox==4.23.2",
    "tox-ansible==24.9.0",
    "tzdata==2024.2",
    "urllib3==2.2.3",
    "virtualenv==20.27.1",
    "wcmatch==10.0",
    "yamllint==1.35.1",
    "zipp==3.21.0",
]
