---
- name: Get all repositories
  uri:
    url: "{{ nexus_protocol }}://{{ nexus_hostname }}:{{ nexus_port }}/service/rest/v1/repositories"
    method: GET
    validate_certs: false
    status_code: 200
    user: "{{ nexus_admin_username }}"
    password: "{{ nexus_admin_password }}"
    force_basic_auth: true
  register: __nexus_repositories__
  until: __nexus_repositories__.status == 200
  retries: 30
  delay: 10

- name: Debug all repositories
  debug:
    var: __nexus_repositories__.json
