# defaults file for nexus3-config-as-code
nexus_protocol: http
nexus_hostname: 172.17.0.3
nexus_port: 8081
nexus_admin_username: admin
nexus_admin_password: changeme
nexus_enable_pro: true

nexus_blobstores:
  - name: default
    type: File
    path: default-21
    softQuota:
      type: spaceRemainingQuota
      limit: 408957600 #100Mb
  - name: default-200
    type: File
    path: default-200
    softQuota:
      type: spaceRemainingQuota
      limit: 104857600 #100Mb
  - name: file-quota-100-remaining
    type: File
    path: default-quota-100-remaining
    softQuota:
      type: spaceRemainingQuota
      limit: 104857600 #100Mb
  - name: file-quota-100-used
    type: File
    path: default-quota-100-used
    softQuota:
      type: spaceUsedQuota
      limit: 104857600 #100Mb
  - name: s3-minio
    type: S3
    softQuota:
      type: spaceUsedQuota
      limit: 104857600 #100Mb
    bucketConfiguration:
      bucket:
        region: us-east-1
        name: nexus-storage
        prefix:
        expiration: 3
      failoverBuckets: []
      bucketSecurity:
        accessKeyId: nexus-access-key
        secretAccessKey: nexus-secret-key
      advancedBucketConnection:
        endpoint: "http://172.17.0.4:9000"
        forcePathStyle: true

nexus_roles:
  - id: "nx-admin"
    name: "nx-admin"
    description: "Administrator Role"
    privileges:
      - "nx-all"
    roles: []
  - id: "nx-anonymous"
    name: "nx-anonymous"
    description: "Anonymous Role"
    privileges:
      - "nx-healthcheck-read"
      - "nx-search-read"
      - "nx-repository-view-*-*-read"
      - "nx-repository-view-*-*-browse"
    roles: []
  - id: "nx-developer"
    name: "nx-developer"
    description: "Developer Role"
    privileges:
      - "nx-repository-view-*-*-read"
      - "nx-repository-view-*-*-browse"
      - "nx-repository-view-*-*-edit"
      - "nx-repository-view-*-*-add"
      - "nx-repository-view-*-*-delete"
  - id: "nx-security-admin"
    name: "nx-security-admin"
    description: "Security Administrator Role"
    privileges:
      - "nx-all"
    roles:
      - "nx-admin"

nexus_anonymous_access:
  enabled: true
  userId: anonymouse
  realmName: NexusAuthorizingRealm

nexus_content_selectors:
  - name: raw-selector
    type: csel
    description: raw-selectorrr
    expression: format == "raw"
  - name: maven-org-selector
    type: csel
    description: maven-org-selectorrr
    expression: format == "maven2" and path =^ "/org"
  - name: maven-com-selector
    type: csel
    description: maven-com-selector
    expression: format == "maven2" and path =^ "/com"

nexus_user_tokens_capability:
  enabled: true
  protectContent: true
  expirationEnabled: true
  expirationDays: 180

# nexus_license_b64: "your-base64-encoded-license-string"
nexus_license_path: ../files/license.lic

nexus_default_user_password: changeme
nexus_users:
  - userId: anonymous
    firstName: Anonymous
    lastName: User
    emailAddress: anonymous@example.org
    source: default
    status: active
    readOnly: false
    roles:
      - nx-anonymous
    externalRoles: []
  - userId: admin
    firstName: Administrator
    lastName: User
    emailAddress: admin@example.org
    source: default
    status: active
    readOnly: false
    roles:
      - nx-admin
    externalRoles: []
  - userId: disabled-user
    firstName: Disabled
    lastName: User
    emailAddress: info@users.org
    source: default
    status: disabled
    readOnly: false
    roles:
      - nx-anonymous
    externalRoles: []
  - userId: secondary-admin
    firstName: Secondary
    lastName: AdminUser
    emailAddress: test@test.com
    source: default
    status: active
    readOnly: false
    roles:
      - nx-anonymous
      - nx-admin
    externalRoles: []
  - userId: read-only-user
    firstName: Read
    lastName: OnlyUser
    emailAddress: readonly@users.org
    source: default
    status: active
    readOnly: true
    roles:
      - nx-anonymous
    externalRoles: []

nexus_repos_cleanup_policies:
  - name: maven_cleanup
    format: maven2
    notes: "maven"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: maven_releases_cleanup
    format: maven2
    notes: "maven RELEASES"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaReleaseType: RELEASES
    criteriaAssetRegex: "your-regex*"
  - name: maven_prereleases_cleanup
    format: maven2
    notes: "maven PRERELEASES"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaReleaseType: PRERELEASES
    criteriaAssetRegex: "your-regex*"
  - name: python_cleanup
    format: pypi
    notes: "Python pip"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: docker_cleanup
    format: docker
    notes: "Docker"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: raw_cleanup
    format: raw
    notes: "Raw"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: rubygems_cleanup
    format: rubygems
    notes: "Rubygems"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: npm_cleanup
    format: npm
    notes: ""
    criteriaAssetRegex: "your-regex*"
  - name: npm_releases_cleanup
    format: npm
    notes: "npm RELEASES"
    criteriaAssetRegex: "your-regex*"
    criteriaReleaseType: RELEASES
  - name: npm_prereleases_cleanup
    format: npm
    notes: "npm PRERELEASES"
    criteriaAssetRegex: "your-regex*"
    criteriaReleaseType: PRERELEASES
  - name: nuget_cleanup
    format: nuget
    notes: "NuGet"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: gitlfs_cleanup
    format: gitlfs
    notes: "gitlfs"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
  - name: yum_prerelease_cleanup
    format: yum
    notes: "yum PRERELEASES"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
    criteriaReleaseType: PRERELEASES
  - name: yum_releases_cleanup
    format: yum
    notes: "yum RELEASES"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
    criteriaReleaseType: PRERELEASES
  - name: yum_cleanup
    format: yum
    notes: "yum"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: apt_cleanup
    format: apt
    notes: "apt"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: helm_cleanup
    format: helm
    notes: "Helm"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: r_cleanup
    format: r
    notes: "r"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: conda_cleanup
    format: conda
    notes: "conda"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: go_cleanup
    format: go
    notes: "go"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: cocoapods_cleanup
    format: cocoapods
    notes: "cocoapods"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: conan_cleanup
    format: conan
    notes: "conan"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"
  - name: p2_cleanup
    format: p2
    notes: "p2-notes"
    criteriaLastBlobUpdated: 60
    criteriaLastDownloaded: 120
    criteriaAssetRegex: "your-regex*"

nexus_repos_maven_hosted:
  - name: repo-1
    cleanup:
      policyNames:
        - maven_cleanup
    component:
      proprietaryComponents: true
    maven:
      versionPolicy: RELEASE
      layoutPolicy: STRICT
      contentDisposition: INLINE
  - name: maven-snapshots
    cleanup:
      policyNames:
        - maven_cleanup
    storage:
      strictContentTypeValidation: true
      writePolicy: ALLOW_ONCE
    maven:
      contentDisposition: INLINE
      layoutPolicy: STRICT
      versionPolicy: SNAPSHOT
    component:
      proprietaryComponents: true

  - name: maven-releases
    online: true
    storage:
      strictContentTypeValidation: true
    maven:
      contentDisposition: INLINE
      layoutPolicy: STRICT
      versionPolicy: RELEASE
    component:
      proprietaryComponents: true
    cleanup:
      policyNames:
        - maven_cleanup

  - name: repo-2
    cleanup:
      policyNames:
        - maven_cleanup

nexus_repos_maven_proxy:
  - name: maven-central
    proxy:
      remoteUrl: https://repo1.maven.org/maven2/
      contentMaxAge: -1
      metadataMaxAge: 1440
    negativeCache:
      enabled: true
      timeToLive: 1440
    httpClient:
      blocked: false
      autoBlock: true
  - name: maven-proxy-2
    proxy:
      remoteUrl: https://repo1.maven.org/maven2/
      contentMaxAge: -1
      metadataMaxAge: 1440
    routingRule: routing-rule-allow-all
  - name: maven-proxy-3
    proxy:
      remoteUrl: https://repo1.maven.org/maven2/
      contentMaxAge: -1
      metadataMaxAge: 1440
    negativeCache:
      enabled: true
      timeToLive: 1440
    httpClient:
      blocked: false
      autoBlock: true

nexus_routing_rules:
  - name: routing-rule-block-nmap
    description: routing-rule-1
    mode: BLOCK
    matchers:
      - ".*nmap"
  - name: routing-rule-allow-patch-update
    description: rrouting-rule-2
    mode: ALLOW
    matchers:
      - ".*patch"
      - ".*update"
  - name: routing-rule-allow-all
    description: routing-rule-3
    mode: ALLOW
    matchers:
      - ".*"
  - name: routing-rule-block-all
    description: routing-rule-4
    mode: BLOCK
    matchers:
      - ".*"
