# defaults file for nexus3-config-as-code
nexus_protocol: http
nexus_hostname: 172.17.0.3
nexus_port: 8081
nexus_admin_username: admin
nexus_admin_password: changeme
nexus_enable_pro: true

nexus_license_b64:
nexus_license_path: ../files/license.lic
