---
- name: Converge
  hosts: nexus
  collections:
    - cloudkrafter.nexus

  roles:
    - role: cloudkrafter.nexus.nexus_oss
      tags: nexus

  vars_files:
    - ssl-{{ ansible_os_family }}.yml
    - nexus_common_test_vars.yml
    - nexus_ldap_test_vars.yml

  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  tasks:
    - name: Gather Nexus information
      cloudkrafter.nexus.gather_info:
        url: http://localhost:8081
        username: admin
        password: changeme
        validate_certs: false
      register: nxrm_instance

    - name: Print nexus facts
      debug:
        var: nxrm_instance

    - name: Print Nexus information
      vars:
        info: |-
          Version: {{ nxrm_instance.node.version }}
          Edition: {{ nxrm_instance.node.edition }}
          Node ID: {{ nxrm_instance.node.node_id }}
          Details: {{ nxrm_instance.node.details is defined }}
      ansible.builtin.debug:
        msg: "{{ info.split('\n') }}"
