---
- name: Converge
  hosts: localhost
  gather_facts: true
  collections:
    - cloudkrafter.nexus

  pre_tasks:
    - name: Install Nexus Pro License
      when: lookup('env', 'NEXUS_LICENSE_B64') | default(false, true)
      block:
        - name: Gather Nexus Node Info
          cloudkrafter.nexus.gather_info:
            url: "{{ nexus_api_scheme }}://{{ nexus_api_hostname }}:{{ nexus_api_port }}"
            username: "{{ nexus_admin_username }}"
            password: "{{ nexus_admin_password }}"
          register: nxrm_instance

        - name: Set facts for Nexus Node
          ansible.builtin.set_fact:
            nexus_pro_version: "{{ nxrm_instance.node.edition == 'PRO' | default(false) }}"

        - name: Include license installation tasks
          ansible.builtin.include_role:
            name: cloudkrafter.nexus.config_api
            tasks_from: license-api.yml
        
        - name: Get Nexus container name
          community.docker.docker_host_info:
            containers: true
          register: nexus_container_info

        - name: Set Nexus container name
          ansible.builtin.set_fact:
            nexus_container_name: >-
              {{
                nexus_container_info.containers |
                selectattr('Image', 'defined') |
                selectattr('Image', 'search', 'sonatype/nexus') |
                map(attribute='Id') |
                first
              }}

        - name: Restart Nexus container
          community.docker.docker_container:
            name: "{{ nexus_container_name }}"
            state: started
            restart: true
          changed_when: false # just to pass idempotence check

        - name: Wait for Nexus API to be available after restart
          ansible.builtin.uri:
            url: "http://localhost:8081/service/rest/v1/status/writable"
            method: GET
            validate_certs: false
            status_code: 200
          register: __nexus_writable__
          until: __nexus_writable__.status == 200
          retries: 30
          delay: 10

  roles:
    - role: cloudkrafter.nexus.config_api
  
  tasks:
    - name: Gather Nexus information
      cloudkrafter.nexus.gather_info:
        url: http://localhost:8081
        username: admin
        password: changeme
        validate_certs: false
      register: nxrm_instance

    - name: Print nexus facts
      debug:
        var: nxrm_instance.node

    - name: Print Nexus information
      vars:
        info: |-
          Version: {{ nxrm_instance.node.version }}
          Edition: {{ nxrm_instance.node.edition }}
          Node ID: {{ nxrm_instance.node.node_id }}
          Details: {{ nxrm_instance.node.details is defined }}
      ansible.builtin.debug:
        msg: "{{ info.split('\n') }}"
