---
- name: Converge
  hosts: localhost
  gather_facts: true
  collections:
    - cloudkrafter.nexus

  pre_tasks:
    - name: Install Nexus Pro License
      when: lookup('env', 'NEXUS_LICENSE_B64') | default(false, true)
      block:
        - name: Include license installation tasks
          ansible.builtin.include_role:
            name: cloudkrafter.nexus.config_api
            tasks_from: license-api.yml

        - name: Restart Nexus container
          community.docker.docker_container:
            name: nexus3-pro
            state: started
            restart: true
          changed_when: false # just to pass idempotence check

        - name: Wait for Nexus API to be available after restart
          ansible.builtin.uri:
            url: "http://localhost:8081/service/rest/v1/status/writable"
            method: GET
            validate_certs: false
            status_code: 200
          register: __nexus_writable__
          until: __nexus_writable__.status == 200
          retries: 30
          delay: 10

  roles:
    - role: cloudkrafter.nexus.config_api
  
  tasks:
    - name: Gather Nexus information
      cloudkrafter.nexus.nexus_info:
        url: http://localhost:8081
        username: admin
        password: changeme
        validate_certs: false

    - name: Print Nexus information
      vars:
        info: |-
          Basic info only: {{ ansible_facts.nexus_info.basic_info }}
          Version: {{ ansible_facts.nexus_info.version }}
          Edition: {{ ansible_facts.nexus_info.edition }}
          Node ID: {{ ansible_facts.nexus_info.node_id }}
      ansible.builtin.debug:
        msg: "{{ info.split('\n') }}"
