---
# This script accepts a list of blobstores to delete
# The blobstores are deleted one by one

- name: Delete blobstores using API
  ansible.builtin.uri:
    url: "{{ nexus_api_scheme }}://{{ nexus_api_hostname }}:{{ nexus_api_port }}{{ nexus_api_context_path }}service/rest/v1/blobstores/{{ item.name }}"
    user: admin
    password: "{{ current_nexus_admin_password }}"
    method: DELETE
    force_basic_auth: true
    validate_certs: "{{ nexus_api_validate_certs }}"
    status_code: 204
    timeout: "{{ nexus_api_timeout | int }}"
  when: >-
    __nexus_existing_blobstores__ is defined and
    __nexus_existing_blobstores__.json | map(attribute='name') | list | intersect([item.name]) | length > 0
