---
driver:
  name: docker

platforms:
  - name: nexus3-pro
    hostname: nexus3-pro
    image: sonatype/nexus3
    pull: true
    pre_build_image: true
    published_ports:
      - 9081:8081
    groups:
      - nexus
    networks: &nexus_networks
      - name: nexus-networks

  # - name: postgresql-server
  #   hostname: postgresql-server
  #   image: postgres:14-bullseye
  #   pull: true
  #   pre_build_image: true
  #   published_ports:
  #     - 5432:5432
  #   env:
  #     POSTGRES_DB: nexus
  #     POSTGRES_USER: nexus
  #     POSTGRES_PASSWORD: nexus
  #   groups:
  #     - postgresql

provisioner:
  name: ansible

scenario:
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - check
    - verify
    - destroy

verifier:
  name: ansible

role_name_check: 2
