name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - ".devcontainer/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".devcontainer/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Set timestamp
        id: set_timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - name: Build the Docker image
        run: docker build -t cloudkrafter/ansible-devcontainer:${{ env.TIMESTAMP }} -f .devcontainer/Dockerfile .
      - name: Tag the Docker image as latest if on main branch
        if: github.ref == 'refs/heads/main'
        run: docker tag cloudkrafter/ansible-devcontainer:${{ env.TIMESTAMP }} cloudkrafter/ansible-devcontainer:latest
      - name: Push the Docker image
        run: docker push cloudkrafter/ansible-devcontainer:${{ env.TIMESTAMP }}
      - name: Push the latest Docker image if on main branch
        if: github.ref == 'refs/heads/main'
        run: docker push cloudkrafter/ansible-devcontainer:latest
