---
name: Publish new version to Galaxy

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag to release'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.release_tag }}

      - name: Update version in galaxy.yml
        run: |
          # Remove 'v' prefix if present in tag name
            VERSION=$(echo ${{ github.event.release.tag_name || github.event.inputs.release_tag }} | sed 's/^v//')
          # Update version in galaxy.yml (Linux syntax)
          sed -i "s/^version: .*/version: $VERSION/" galaxy.yml

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible.
        run: pip3 install -r requirements.txt

      - name: Build collection
        run: ansible-galaxy collection build

      - name: Publish to Galaxy.
        run: ansible-galaxy collection publish cloudkrafter-nexus-*.tar.gz --token ${{ secrets.GALAXY_API_KEY }}
