---
name: Publish new version to Galaxy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible.
        run: pip3 install -r requirements.txt

      - name: Trigger a new import on Galaxy.
        run: ansible-galaxy role import --token ${{ secrets.GALAXY_API_KEY }} --branch main $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
