name: Molecule Test

on:
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10','3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-docker ansible ansible-core docker pytest
          ansible-galaxy collection install community.general
          ansible-galaxy collection install community.docker

      - name: Create Docker Network
        run: docker network create nexus

      - name: Run Molecule tests
        run: molecule test -s default-community
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DOCKER_NETWORK: test-network
  