name: Molecule Test

on:
  push:
    paths:
      - 'molecule/**'
      - 'roles/**'
      - '.github/workflows/**'
  pull_request:
    types: [review_requested]
  workflow_dispatch:
    inputs:
      nexus_version:
        description: 'Nexus version to test (e.g., 3.58.1)'
        required: false
        default: 'latest'
        type: string

jobs:  
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - default-community

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests.
        run: molecule test -s ${{ matrix.distro }} -- -vv
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          NEXUS_VERSION: ${{ github.event.inputs.nexus_version || 'latest' }}
